# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/drachiologe/Fleckenstein/C++/dragonblocks-dev

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/drachiologe/Fleckenstein/C++/dragonblocks-dev

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/drachiologe/Fleckenstein/C++/dragonblocks-dev/CMakeFiles /media/drachiologe/Fleckenstein/C++/dragonblocks-dev/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/drachiologe/Fleckenstein/C++/dragonblocks-dev/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dragonblocks

# Build rule for target.
dragonblocks: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dragonblocks
.PHONY : dragonblocks

# fast build rule for target.
dragonblocks/fast:
	$(MAKE) -f CMakeFiles/dragonblocks.dir/build.make CMakeFiles/dragonblocks.dir/build
.PHONY : dragonblocks/fast

src/entity.o: src/entity.cpp.o

.PHONY : src/entity.o

# target to build an object file
src/entity.cpp.o:
	$(MAKE) -f CMakeFiles/dragonblocks.dir/build.make CMakeFiles/dragonblocks.dir/src/entity.cpp.o
.PHONY : src/entity.cpp.o

src/entity.i: src/entity.cpp.i

.PHONY : src/entity.i

# target to preprocess a source file
src/entity.cpp.i:
	$(MAKE) -f CMakeFiles/dragonblocks.dir/build.make CMakeFiles/dragonblocks.dir/src/entity.cpp.i
.PHONY : src/entity.cpp.i

src/entity.s: src/entity.cpp.s

.PHONY : src/entity.s

# target to generate assembly for a file
src/entity.cpp.s:
	$(MAKE) -f CMakeFiles/dragonblocks.dir/build.make CMakeFiles/dragonblocks.dir/src/entity.cpp.s
.PHONY : src/entity.cpp.s

src/game.o: src/game.cpp.o

.PHONY : src/game.o

# target to build an object file
src/game.cpp.o:
	$(MAKE) -f CMakeFiles/dragonblocks.dir/build.make CMakeFiles/dragonblocks.dir/src/game.cpp.o
.PHONY : src/game.cpp.o

src/game.i: src/game.cpp.i

.PHONY : src/game.i

# target to preprocess a source file
src/game.cpp.i:
	$(MAKE) -f CMakeFiles/dragonblocks.dir/build.make CMakeFiles/dragonblocks.dir/src/game.cpp.i
.PHONY : src/game.cpp.i

src/game.s: src/game.cpp.s

.PHONY : src/game.s

# target to generate assembly for a file
src/game.cpp.s:
	$(MAKE) -f CMakeFiles/dragonblocks.dir/build.make CMakeFiles/dragonblocks.dir/src/game.cpp.s
.PHONY : src/game.cpp.s

src/graphics.o: src/graphics.cpp.o

.PHONY : src/graphics.o

# target to build an object file
src/graphics.cpp.o:
	$(MAKE) -f CMakeFiles/dragonblocks.dir/build.make CMakeFiles/dragonblocks.dir/src/graphics.cpp.o
.PHONY : src/graphics.cpp.o

src/graphics.i: src/graphics.cpp.i

.PHONY : src/graphics.i

# target to preprocess a source file
src/graphics.cpp.i:
	$(MAKE) -f CMakeFiles/dragonblocks.dir/build.make CMakeFiles/dragonblocks.dir/src/graphics.cpp.i
.PHONY : src/graphics.cpp.i

src/graphics.s: src/graphics.cpp.s

.PHONY : src/graphics.s

# target to generate assembly for a file
src/graphics.cpp.s:
	$(MAKE) -f CMakeFiles/dragonblocks.dir/build.make CMakeFiles/dragonblocks.dir/src/graphics.cpp.s
.PHONY : src/graphics.cpp.s

src/inventory.o: src/inventory.cpp.o

.PHONY : src/inventory.o

# target to build an object file
src/inventory.cpp.o:
	$(MAKE) -f CMakeFiles/dragonblocks.dir/build.make CMakeFiles/dragonblocks.dir/src/inventory.cpp.o
.PHONY : src/inventory.cpp.o

src/inventory.i: src/inventory.cpp.i

.PHONY : src/inventory.i

# target to preprocess a source file
src/inventory.cpp.i:
	$(MAKE) -f CMakeFiles/dragonblocks.dir/build.make CMakeFiles/dragonblocks.dir/src/inventory.cpp.i
.PHONY : src/inventory.cpp.i

src/inventory.s: src/inventory.cpp.s

.PHONY : src/inventory.s

# target to generate assembly for a file
src/inventory.cpp.s:
	$(MAKE) -f CMakeFiles/dragonblocks.dir/build.make CMakeFiles/dragonblocks.dir/src/inventory.cpp.s
.PHONY : src/inventory.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/dragonblocks.dir/build.make CMakeFiles/dragonblocks.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/dragonblocks.dir/build.make CMakeFiles/dragonblocks.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/dragonblocks.dir/build.make CMakeFiles/dragonblocks.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/map.o: src/map.cpp.o

.PHONY : src/map.o

# target to build an object file
src/map.cpp.o:
	$(MAKE) -f CMakeFiles/dragonblocks.dir/build.make CMakeFiles/dragonblocks.dir/src/map.cpp.o
.PHONY : src/map.cpp.o

src/map.i: src/map.cpp.i

.PHONY : src/map.i

# target to preprocess a source file
src/map.cpp.i:
	$(MAKE) -f CMakeFiles/dragonblocks.dir/build.make CMakeFiles/dragonblocks.dir/src/map.cpp.i
.PHONY : src/map.cpp.i

src/map.s: src/map.cpp.s

.PHONY : src/map.s

# target to generate assembly for a file
src/map.cpp.s:
	$(MAKE) -f CMakeFiles/dragonblocks.dir/build.make CMakeFiles/dragonblocks.dir/src/map.cpp.s
.PHONY : src/map.cpp.s

src/mapgen.o: src/mapgen.cpp.o

.PHONY : src/mapgen.o

# target to build an object file
src/mapgen.cpp.o:
	$(MAKE) -f CMakeFiles/dragonblocks.dir/build.make CMakeFiles/dragonblocks.dir/src/mapgen.cpp.o
.PHONY : src/mapgen.cpp.o

src/mapgen.i: src/mapgen.cpp.i

.PHONY : src/mapgen.i

# target to preprocess a source file
src/mapgen.cpp.i:
	$(MAKE) -f CMakeFiles/dragonblocks.dir/build.make CMakeFiles/dragonblocks.dir/src/mapgen.cpp.i
.PHONY : src/mapgen.cpp.i

src/mapgen.s: src/mapgen.cpp.s

.PHONY : src/mapgen.s

# target to generate assembly for a file
src/mapgen.cpp.s:
	$(MAKE) -f CMakeFiles/dragonblocks.dir/build.make CMakeFiles/dragonblocks.dir/src/mapgen.cpp.s
.PHONY : src/mapgen.cpp.s

src/mods.o: src/mods.cpp.o

.PHONY : src/mods.o

# target to build an object file
src/mods.cpp.o:
	$(MAKE) -f CMakeFiles/dragonblocks.dir/build.make CMakeFiles/dragonblocks.dir/src/mods.cpp.o
.PHONY : src/mods.cpp.o

src/mods.i: src/mods.cpp.i

.PHONY : src/mods.i

# target to preprocess a source file
src/mods.cpp.i:
	$(MAKE) -f CMakeFiles/dragonblocks.dir/build.make CMakeFiles/dragonblocks.dir/src/mods.cpp.i
.PHONY : src/mods.cpp.i

src/mods.s: src/mods.cpp.s

.PHONY : src/mods.s

# target to generate assembly for a file
src/mods.cpp.s:
	$(MAKE) -f CMakeFiles/dragonblocks.dir/build.make CMakeFiles/dragonblocks.dir/src/mods.cpp.s
.PHONY : src/mods.cpp.s

src/node.o: src/node.cpp.o

.PHONY : src/node.o

# target to build an object file
src/node.cpp.o:
	$(MAKE) -f CMakeFiles/dragonblocks.dir/build.make CMakeFiles/dragonblocks.dir/src/node.cpp.o
.PHONY : src/node.cpp.o

src/node.i: src/node.cpp.i

.PHONY : src/node.i

# target to preprocess a source file
src/node.cpp.i:
	$(MAKE) -f CMakeFiles/dragonblocks.dir/build.make CMakeFiles/dragonblocks.dir/src/node.cpp.i
.PHONY : src/node.cpp.i

src/node.s: src/node.cpp.s

.PHONY : src/node.s

# target to generate assembly for a file
src/node.cpp.s:
	$(MAKE) -f CMakeFiles/dragonblocks.dir/build.make CMakeFiles/dragonblocks.dir/src/node.cpp.s
.PHONY : src/node.cpp.s

src/player.o: src/player.cpp.o

.PHONY : src/player.o

# target to build an object file
src/player.cpp.o:
	$(MAKE) -f CMakeFiles/dragonblocks.dir/build.make CMakeFiles/dragonblocks.dir/src/player.cpp.o
.PHONY : src/player.cpp.o

src/player.i: src/player.cpp.i

.PHONY : src/player.i

# target to preprocess a source file
src/player.cpp.i:
	$(MAKE) -f CMakeFiles/dragonblocks.dir/build.make CMakeFiles/dragonblocks.dir/src/player.cpp.i
.PHONY : src/player.cpp.i

src/player.s: src/player.cpp.s

.PHONY : src/player.s

# target to generate assembly for a file
src/player.cpp.s:
	$(MAKE) -f CMakeFiles/dragonblocks.dir/build.make CMakeFiles/dragonblocks.dir/src/player.cpp.s
.PHONY : src/player.cpp.s

src/texture.o: src/texture.cpp.o

.PHONY : src/texture.o

# target to build an object file
src/texture.cpp.o:
	$(MAKE) -f CMakeFiles/dragonblocks.dir/build.make CMakeFiles/dragonblocks.dir/src/texture.cpp.o
.PHONY : src/texture.cpp.o

src/texture.i: src/texture.cpp.i

.PHONY : src/texture.i

# target to preprocess a source file
src/texture.cpp.i:
	$(MAKE) -f CMakeFiles/dragonblocks.dir/build.make CMakeFiles/dragonblocks.dir/src/texture.cpp.i
.PHONY : src/texture.cpp.i

src/texture.s: src/texture.cpp.s

.PHONY : src/texture.s

# target to generate assembly for a file
src/texture.cpp.s:
	$(MAKE) -f CMakeFiles/dragonblocks.dir/build.make CMakeFiles/dragonblocks.dir/src/texture.cpp.s
.PHONY : src/texture.cpp.s

src/threads.o: src/threads.cpp.o

.PHONY : src/threads.o

# target to build an object file
src/threads.cpp.o:
	$(MAKE) -f CMakeFiles/dragonblocks.dir/build.make CMakeFiles/dragonblocks.dir/src/threads.cpp.o
.PHONY : src/threads.cpp.o

src/threads.i: src/threads.cpp.i

.PHONY : src/threads.i

# target to preprocess a source file
src/threads.cpp.i:
	$(MAKE) -f CMakeFiles/dragonblocks.dir/build.make CMakeFiles/dragonblocks.dir/src/threads.cpp.i
.PHONY : src/threads.cpp.i

src/threads.s: src/threads.cpp.s

.PHONY : src/threads.s

# target to generate assembly for a file
src/threads.cpp.s:
	$(MAKE) -f CMakeFiles/dragonblocks.dir/build.make CMakeFiles/dragonblocks.dir/src/threads.cpp.s
.PHONY : src/threads.cpp.s

src/util.o: src/util.cpp.o

.PHONY : src/util.o

# target to build an object file
src/util.cpp.o:
	$(MAKE) -f CMakeFiles/dragonblocks.dir/build.make CMakeFiles/dragonblocks.dir/src/util.cpp.o
.PHONY : src/util.cpp.o

src/util.i: src/util.cpp.i

.PHONY : src/util.i

# target to preprocess a source file
src/util.cpp.i:
	$(MAKE) -f CMakeFiles/dragonblocks.dir/build.make CMakeFiles/dragonblocks.dir/src/util.cpp.i
.PHONY : src/util.cpp.i

src/util.s: src/util.cpp.s

.PHONY : src/util.s

# target to generate assembly for a file
src/util.cpp.s:
	$(MAKE) -f CMakeFiles/dragonblocks.dir/build.make CMakeFiles/dragonblocks.dir/src/util.cpp.s
.PHONY : src/util.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... dragonblocks"
	@echo "... edit_cache"
	@echo "... src/entity.o"
	@echo "... src/entity.i"
	@echo "... src/entity.s"
	@echo "... src/game.o"
	@echo "... src/game.i"
	@echo "... src/game.s"
	@echo "... src/graphics.o"
	@echo "... src/graphics.i"
	@echo "... src/graphics.s"
	@echo "... src/inventory.o"
	@echo "... src/inventory.i"
	@echo "... src/inventory.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/map.o"
	@echo "... src/map.i"
	@echo "... src/map.s"
	@echo "... src/mapgen.o"
	@echo "... src/mapgen.i"
	@echo "... src/mapgen.s"
	@echo "... src/mods.o"
	@echo "... src/mods.i"
	@echo "... src/mods.s"
	@echo "... src/node.o"
	@echo "... src/node.i"
	@echo "... src/node.s"
	@echo "... src/player.o"
	@echo "... src/player.i"
	@echo "... src/player.s"
	@echo "... src/texture.o"
	@echo "... src/texture.i"
	@echo "... src/texture.s"
	@echo "... src/threads.o"
	@echo "... src/threads.i"
	@echo "... src/threads.s"
	@echo "... src/util.o"
	@echo "... src/util.i"
	@echo "... src/util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

