dragonblocks.log(" ____                              _     _            _         ")
dragonblocks.log("|  _ \\ _ __ __ _  __ _  ___  _ __ | |__ | | ___   ___| | _____  ")
dragonblocks.log("| | | | '__/ _` |/ _` |/ _ \\| '_ \\| '_ \\| |/ _ \\ / __| |/ / __| ")
dragonblocks.log("| |_| | | | (_| | (_| | (_) | | | | |_) | | (_) | (__|   <\\__ \\ ")
dragonblocks.log("|____/|_|  \\__,_|\\__, |\\___/|_| |_|_.__/|_|\\___/ \\___|_|\\_\\___/ ")
dragonblocks.log("                 |___/                                          ")
dofile("mods/dragonblocks/nodes.lua")
